// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbPaBE7FTchnZp0XraW_-Hv4Gv8etdLKA',
    appId: '1:609348516413:web:b6f8278b93dfa3a35a0854',
    messagingSenderId: '609348516413',
    projectId: 'musayi-6481a',
    authDomain: 'musayi-6481a.firebaseapp.com',
    storageBucket: 'musayi-6481a.appspot.com',
    measurementId: 'G-L71FXTQBCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArVwSC45ULDGbJfWhT40BlA8_RNOyRgco',
    appId: '1:609348516413:android:3011148f4f3833895a0854',
    messagingSenderId: '609348516413',
    projectId: 'musayi-6481a',
    storageBucket: 'musayi-6481a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtVGMfIzJO_PzDXyTnoRDAXWCmaPeDEy0',
    appId: '1:609348516413:ios:6382d3efbbed9a415a0854',
    messagingSenderId: '609348516413',
    projectId: 'musayi-6481a',
    storageBucket: 'musayi-6481a.appspot.com',
    iosClientId: '609348516413-34qa9nftr6ji1e56q6abnq7f60cf3290.apps.googleusercontent.com',
    iosBundleId: 'com.example.musayi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtVGMfIzJO_PzDXyTnoRDAXWCmaPeDEy0',
    appId: '1:609348516413:ios:6382d3efbbed9a415a0854',
    messagingSenderId: '609348516413',
    projectId: 'musayi-6481a',
    storageBucket: 'musayi-6481a.appspot.com',
    iosClientId: '609348516413-34qa9nftr6ji1e56q6abnq7f60cf3290.apps.googleusercontent.com',
    iosBundleId: 'com.example.musayi',
  );
}
